export const FETCH_BOOKLIST_REQUEST = "FETCH_BOOKLIST_REQUEST";
export const FETCH_BOOKLIST_SUCCESS = "FETCH_BOOKLIST_SUCCESS";
export const FETCH_BOOKLIST_FAILURE = "FETCH_BOOKLIST_FAILURE";

export const ADD_NEW_BOOK = "ADD_NEW_BOOK";
